import java.util.ArrayList;
import java.io.IOException;
import java.io.FileWriter;

public class Groups {
	private int numberOfPeople;
	private ArrayList<Student> group;

    public Groups() {
        numberOfPeople = 0;
        group = new ArrayList<Student>();
    }

    public void addStudent(Student s) {
       group.add(s);
       numberOfPeople++;
    }

    public void writeCSV(FileWriter writer) {
       try {
    	   for (Student s : group) {
               writer.append(s.getName());
               writer.append(',');
               writer.append(s.getEmail());
               writer.append('\n');
            }
            writer.append('\n');
         } catch (IOException e) {
            e.printStackTrace();
         }
     }

	public int getNumberOfPeople() {
         return numberOfPeople;
     }

    // autogenerated methods
    @Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((group == null) ? 0 : group.hashCode());
		result = prime * result + numberOfPeople;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Groups other = (Groups) obj;
		if (group == null) {
			if (other.group != null)
				return false;
		} else {
			for (Student g : other.group) {
				if (!group.contains(g))
					return false;
			}
		}
		if (numberOfPeople != other.numberOfPeople)
			return false;
		return true;
	}

	@Override
      public String toString() {
         String people = "";
         for (Student s: group) {
            people += s.getName() + ": " + s.getEmail() + "\n";
         }
         return people;
      }
}
